### ISSUE TITLE
beets-1.3.13 no longer has echonest_tempo plugin

### ISSUE THREAD

**Issue by jeeger** [sdfg2/sdfg-overlay#4]
Hey! Your beets-1.3.13 ebuild still contains the "echonest_tempo" plugin, which is no longer present in the beets code, causing the ebuild to fail.

**Comment by sdfg2** [comment]
I can't replicate the build error, but you're right, that plugin has been rolled into the echonest plugin itself.  However, that has led to a nice little merry dance making a new ebuild for pyechonest-8.0.1. :-)
